---
name: Python linting

"on":
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Running ruff
        run: |
          pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install -r requirements.txt -r requirements-dev.txt
          pip install .
          ruff tests vigil *.py
          mypy tests vigil *.py
